[package]
edition = "2024"
name = "snapshot-testing"
version = "0.1.0" # Keep in sync with README.md audit command
description = "Assert that a multi-line string equals the contents of an easily updatable snapshot file. Print a nice colored diff if not."
homepage = "https://github.com/Enselic/snapshot-testing"
documentation = "https://docs.rs/snapshot-testing"
readme = "README.md"
keywords = ["snapshot", "testing"]
license = "Unlicense"
repository = "https://github.com/Enselic/snapshot-testing"

# We use the same nice underlying colored diff engine that insta is using.
[dependencies.similar-asserts]
version = "1.7.0"
default-features = false

[dev-dependencies]
# We could use the tempfile crate instead of creating a random directory
# ourselves, but the Cargo.lock file becomes significantly shorter if we do it
# ourselves. And we want this crate to be easy to audit.
fastrand = "2.3.0"
