permissions:
  contents: none # Minimal default permissions

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    permissions:
      contents: read # For actions/checkout@v4 in ci.yml
    uses: ./.github/workflows/ci.yml

  release:
    needs: ci
    environment:
      name: crates.io
      url: https://crates.io/crates/snapshot-testing
    runs-on: ubuntu-latest
    permissions:
      contents: write # git push
      id-token: write # https://crates.io/docs/trusted-publishing
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      # Figure out what tag to use
      - name: calculate version
        id: version
        run: |
          version=$(cargo read-manifest --manifest-path Cargo.toml | jq --raw-output .version)
          echo "GIT_TAG=v${version}" >> $GITHUB_OUTPUT

      # Try to cargo publish. If this succeeds we will tag the
      # release. This is because we don't want to have a situation where a
      # version exists at crates.io but not as a git tag.
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      # Push the tag to git.
      - name: push tag
        run: |
          git tag ${{ steps.version.outputs.GIT_TAG }}
          git push origin ${{ steps.version.outputs.GIT_TAG }}
